import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'


import Nav from '../components/Nav'
import Header from '../components/Header'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<div className={styles.container}>

<Nav/>
<Header/>


</div>
  
    </div>
  )
}
